name: ppl
channels:
  - conda-forge
dependencies:
  - black-jupyter
  - isort=5.10.1
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_nbextensions_configurator=0.4.1
  - jupyter=1.0.0
  - jupyterlab=3.4.3
  - jupytext=1.13.8
  - matplotlib=3.5.2
  - numpy=1.22.4
  - pandas=1.4.2
  - pip=22.1.2
  - pymc=4.1.5
  - python-graphviz=0.20
  - python=3.10.4
  - rise=5.7.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - statsmodels==0.13.2
  - tqdm==4.64.1
  - pip:
      - bambi @ git+https://github.com/bambinos/bambi@e05daf1de6e5ca3c111b9221f44d3939c1aaaf82
